from typing import List, Dict, TypedDict, Optional

class CuratedStation(TypedDict):
    name: str
    countryCode: Optional[str]

CURATED_STATIONS: Dict[str, List[CuratedStation]] = {
  'Asia': [
    { "name": "Mirchi", "countryCode": "IN" },
    { "name": "Radio City Hindi", "countryCode": "IN" },
    { "name": "Vividh Bharati", "countryCode": "IN" },
    { "name": "Red FM", "countryCode": "IN" },
    { "name": "AIR Fm Gold Delhi", "countryCode": "IN" },
    { "name": "FM 100 Pakistan", "countryCode": "PK" },
    { "name": "City FM 89", "countryCode": "PK" },
    { "name": "Peoples Radio 91.6 FM", "countryCode": "BD" },
    { "name": "Dhaka FM 90.4", "countryCode": "BD" },
    { "name": "Radio Bhumi", "countryCode": "BD" },
    { "name": "Yangon City FM", "countryCode": "MM" },
    { "name": "EFM 94", "countryCode": "TH" },
    { "name": "Cool Fahrenheit", "countryCode": "TH" },
    { "name": "YES 933", "countryCode": "SG" },
    { "name": "987 FM", "countryCode": "SG" },
    { "name": "HITZ FM", "countryCode": "MY" },
    { "name": "ERA FM", "countryCode": "MY" },
    { "name": "Prambors FM", "countryCode": "ID" },
    { "name": "Gen FM", "countryCode": "ID" },
    { "name": "Big FM 106.2", "countryCode": "AE" },
    { "name": "CNR-1 中国之声", "countryCode": "CN" },
    { "name": "CNR-3 音乐之声", "countryCode": "CN" },
    { "name": "Hit FM 107.7 Taiwan", "countryCode": "TW" },
    { "name": "SBS Power FM", "countryCode": "KR" },
    { "name": "MBC FM4U", "countryCode": "KR" },
    { "name": "Arirang FM", "countryCode": "KR" },
    { "name": "J-WAVE 81.3 FM", "countryCode": "JP" },
    { "name": "Tokyo FM", "countryCode": "JP" },
    { "name": "NHK FM", "countryCode": "JP" }
  ],
  'Europe': [
    { "name": "BBC Radio 1", "countryCode": "GB" },
    { "name": "BBC Radio 2", "countryCode": "GB" },
    { "name": "BBC Radio 4", "countryCode": "GB" },
    { "name": "Capital London", "countryCode": "GB" },
    { "name": "Heart London", "countryCode": "GB" },
    { "name": "Kiss FM", "countryCode": "GB" },
    { "name": "NRJ", "countryCode": "FR" },
    { "name": "France Inter", "countryCode": "FR" },
    { "name": "RFI Monde", "countryCode": "FR" },
    { "name": "Skyrock", "countryCode": "FR" },
    { "name": "RTL", "countryCode": "FR" },
    { "name": "Europe 1", "countryCode": "FR" },
    { "name": "Deutschlandfunk", "countryCode": "DE" },
    { "name": "Bayern 3", "countryCode": "DE" },
    { "name": "Antenne Bayern", "countryCode": "DE" },
    { "name": "NDR 2", "countryCode": "DE" },
    { "name": "Radio Eins", "countryCode": "DE" },
    { "name": "RAI Radio 1", "countryCode": "IT" },
    { "name": "RAI Radio 2", "countryCode": "IT" },
    { "name": "Radio Deejay", "countryCode": "IT" },
    { "name": "Radio 105", "countryCode": "IT" },
    { "name": "Virgin Radio", "countryCode": "IT" },
    { "name": "Los 40", "countryCode": "ES" },
    { "name": "Cadena SER", "countryCode": "ES" },
    { "name": "Onda Cero", "countryCode": "ES" },
    { "name": "Kiss FM Spain", "countryCode": "ES" },
    { "name": "Europa FM", "countryCode": "ES" },
    { "name": "Radio 538", "countryCode": "NL" },
    { "name": "Qmusic", "countryCode": "NL" },
    { "name": "NPO Radio 2", "countryCode": "NL" },
    { "name": "NPO 3FM", "countryCode": "NL" },
    { "name": "Studio Brussel", "countryCode": "BE" },
    { "name": "VRT Radio 2", "countryCode": "BE" },
    { "name": "MNM", "countryCode": "BE" },
    { "name": "RMF FM", "countryCode": "PL" },
    { "name": "Radio Zet", "countryCode": "PL" },
    { "name": "Radio Eska", "countryCode": "PL" },
    { "name": "Sveriges Radio P3", "countryCode": "SE" },
    { "name": "Sveriges Radio P4", "countryCode": "SE" },
    { "name": "NRK P3", "countryCode": "NO" },
    { "name": "NRK P1", "countryCode": "NO" },
    { "name": "DR P3", "countryCode": "DK" },
    { "name": "DR P4", "countryCode": "DK" },
    { "name": "Yle Radio Suomi", "countryCode": "FI" },
    { "name": "YleX", "countryCode": "FI" },
    { "name": "Rádio Comercial", "countryCode": "PT" },
    { "name": "TSF Rádio Notícias", "countryCode": "PT" },
    { "name": "RFM", "countryCode": "PT" },
    { "name": "SRF 1", "countryCode": "CH" },
    { "name": "SRF 3", "countryCode": "CH" },
    { "name": "Radio Energy", "countryCode": "CH" },
    { "name": "Europa Plus", "countryCode": "RU" },
    { "name": "Radio Mayak", "countryCode": "RU" },
    { "name": "Radio Monte Carlo", "countryCode": "RU" },
    { "name": "Ö3", "countryCode": "AT" },
    { "name": "FM4", "countryCode": "AT" },
    { "name": "Radiožurnál", "countryCode": "CZ" },
    { "name": "Evropa 2", "countryCode": "CZ" },
    { "name": "Sfera 102.2", "countryCode": "GR" },
    { "name": "Athens DeeJay 95.2", "countryCode": "GR" }
  ],
  'North America': [
    { "name": "NPR News", "countryCode": "US" },
    { "name": "KEXP", "countryCode": "US" },
    { "name": "KIIS FM", "countryCode": "US" },
    { "name": "Z100 New York", "countryCode": "US" },
    { "name": "Power 106", "countryCode": "US" },
    { "name": "Hot 97 New York", "countryCode": "US" },
    { "name": "CBC Radio One Toronto", "countryCode": "CA" },
    { "name": "CBC Music Vancouver", "countryCode": "CA" },
    { "name": "CHUM FM 104.5", "countryCode": "CA" },
    { "name": "Virgin Radio Toronto", "countryCode": "CA" },
    { "name": "Kiss 92.5 Toronto", "countryCode": "CA" },
    { "name": "Los 40 México", "countryCode": "MX" },
    { "name": "Exa FM 104.9 Mexico", "countryCode": "MX" },
    { "name": "W Radio Mexico", "countryCode": "MX" },
    { "name": "Radio Fórmula 103.3", "countryCode": "MX" },
    { "name": "Ke Buena", "countryCode": "MX" },
    { "name": "Radio Monumental", "countryCode": "CR" },
    { "name": "94.7 FM", "countryCode": "CR" },
    { "name": "Z101", "countryCode": "DO" },
    { "name": "La Mega Dominicana", "countryCode": "DO" },
    { "name": "Radio Rebelde", "countryCode": "CU" },
    { "name": "Radio Habana Cuba", "countryCode": "CU" }
  ],
  'South America': [
    { "name": "Jovem Pan", "countryCode": "BR" },
    { "name": "Rádio Globo", "countryCode": "BR" },
    { "name": "Mix FM", "countryCode": "BR" },
    { "name": "Band FM", "countryCode": "BR" },
    { "name": "Antena 1", "countryCode": "BR" },
    { "name": "Radio Mitre", "countryCode": "AR" },
    { "name": "La 100", "countryCode": "AR" },
    { "name": "Rock & Pop", "countryCode": "AR" },
    { "name": "Radio Nacional Argentina", "countryCode": "AR" },
    { "name": "FM Metro 95.1", "countryCode": "AR" },
    { "name": "Radio Bio Bio", "countryCode": "CL" },
    { "name": "Radio Cooperativa Chile", "countryCode": "CL" },
    { "name": "Rock & Pop 94.1 Chile", "countryCode": "CL" },
    { "name": "Los 40 Chile", "countryCode": "CL" },
    { "name": "Caracol Radio Bogotá", "countryCode": "CO" },
    { "name": "W Radio Colombia", "countryCode": "CO" },
    { "name": "La FM Colombia", "countryCode": "CO" },
    { "name": "Los 40 Colombia", "countryCode": "CO" },
    { "name": "RPP Noticias", "countryCode": "PE" },
    { "name": "Radio Moda Peru", "countryCode": "PE" },
    { "name": "Studio 92 Peru", "countryCode": "PE" },
    { "name": "Unión Radio Venezuela", "countryCode": "VE" },
    { "name": "Éxitos FM 99.7", "countryCode": "VE" },
    { "name": "La Mega Venezuela", "countryCode": "VE" },
    { "name": "El Espectador Uruguay", "countryCode": "UY" },
    { "name": "Radio Carve 850", "countryCode": "UY" },
    { "name": "Océano FM 93.9", "countryCode": "UY" },
    { "name": "Radio Sucre Ecuador", "countryCode": "EC" },
    { "name": "Radio La Red 102.1", "countryCode": "EC" },
    { "name": "Radio Visión Ecuador", "countryCode": "EC" },
    { "name": "Radio Panamericana Bolivia", "countryCode": "BO" },
    { "name": "Fides Radio Bolivia", "countryCode": "BO" },
    { "name": "Monumental AM 1080", "countryCode": "PY" },
    { "name": "Rock & Pop 95.5 Paraguay", "countryCode": "PY" }
  ],
  'Africa': [
    { "name": "Metro FM", "countryCode": "ZA" },
    { "name": "5FM South Africa", "countryCode": "ZA" },
    { "name": "Kaya FM 95.9", "countryCode": "ZA" },
    { "name": "Jacaranda FM 94.2", "countryCode": "ZA" },
    { "name": "Cool FM 96.9 Lagos", "countryCode": "NG" },
    { "name": "Wazobia FM 95.1 Lagos", "countryCode": "NG" },
    { "name": "The Beat 99.9 FM", "countryCode": "NG" },
    { "name": "Nigeria Info 99.3", "countryCode": "NG" },
    { "name": "Capital FM Kenya", "countryCode": "KE" },
    { "name": "Radio Jambo Kenya", "countryCode": "KE" },
    { "name": "Kiss FM Kenya", "countryCode": "KE" },
    { "name": "Nogoum FM Egypt", "countryCode": "EG" },
    { "name": "Nile FM Egypt", "countryCode": "EG" },
    { "name": "Radio Masr Egypt", "countryCode": "EG" },
    { "name": "Joy FM 99.7 Accra", "countryCode": "GH" },
    { "name": "Citi FM 97.3 Accra", "countryCode": "GH" },
    { "name": "Peace FM 104.3", "countryCode": "GH" },
    { "name": "Hit Radio Maroc", "countryCode": "MA" },
    { "name": "Radio 2M Maroc", "countryCode": "MA" },
    { "name": "Clouds FM Tanzania", "countryCode": "TZ" },
    { "name": "Wasafi FM 88.9", "countryCode": "TZ" },
    { "name": "Capital FM Uganda", "countryCode": "UG" },
    { "name": "Radio One FM 90", "countryCode": "UG" },
    { "name": "Sheger FM 102.1", "countryCode": "ET" },
    { "name": "Fana FM 98.1", "countryCode": "ET" },
    { "name": "RFM 94.0 Dakar", "countryCode": "SN" },
    { "name": "Sud FM 98.5", "countryCode": "SN" }
  ],
  'Oceania': [
    { "name": "Triple J", "countryCode": "AU" },
    { "name": "Nova 96.9", "countryCode": "AU" },
    { "name": "KIIS 1065", "countryCode": "AU" },
    { "name": "ABC Radio National Australia", "countryCode": "AU" },
    { "name": "SBS Radio 1 Australia", "countryCode": "AU" },
    { "name": "ZM", "countryCode": "NZ" },
    { "name": "The Edge", "countryCode": "NZ" },
    { "name": "RNZ National", "countryCode": "NZ" },
    { "name": "More FM Auckland", "countryCode": "NZ" },
    { "name": "FBC Radio Fiji", "countryCode": "FJ" },
    { "name": "Legend FM Fiji", "countryCode": "FJ" },
    { "name": "NBC Radio PNG", "countryCode": "PG" },
    { "name": "FM100 PNG", "countryCode": "PG" },
    { "name": "Radio 2AP Samoa", "countryCode": "WS" },
    { "name": "Radio Tonga", "countryCode": "TO" }
  ],
  'Arab World': [
    { "name": "MBC FM", "countryCode": "SA" },
    { "name": "Rotana FM", "countryCode": "SA" },
    { "name": "Panorama FM", "countryCode": "SA" },
    { "name": "UFM Radio", "countryCode": "SA" },
    { "name": "Dubai Eye 103.8", "countryCode": "AE" },
    { "name": "Virgin Radio Dubai", "countryCode": "AE" },
    { "name": "Al Arabiya 99 FM", "countryCode": "AE" },
    { "name": "Al Khaleejiya", "countryCode": "AE" },
    { "name": "Nogoum FM Egypt", "countryCode": "EG" },
    { "name": "Nile FM Egypt", "countryCode": "EG" },
    { "name": "Radio Masr", "countryCode": "EG" },
    { "name": "Shaabi FM 95", "countryCode": "EG" },
    { "name": "Mazaj FM", "countryCode": "JO" },
    { "name": "Play 99.6", "countryCode": "JO" },
    { "name": "Beat FM Jordan", "countryCode": "JO" },
    { "name": "Radio One Lebanon", "countryCode": "LB" },
    { "name": "Sawt El Ghad", "countryCode": "LB" },
    { "name": "NRJ Lebanon", "countryCode": "LB" },
    { "name": "Qatar Radio", "countryCode": "QA" },
    { "name": "QBS Radio", "countryCode": "QA" },
    { "name": "Marina FM", "countryCode": "KW" },
    { "name": "Super FM 99.7", "countryCode": "KW" },
    { "name": "Radio Bahrain 96.5", "countryCode": "BH" },
    { "name": "Hi FM 95.9", "countryCode": "OM" },
    { "name": "Merge 104.8", "countryCode": "OM" },
    { "name": "Hit Radio Maroc", "countryCode": "MA" },
    { "name": "Medi 1", "countryCode": "MA" },
    { "name": "Radio 2M Maroc", "countryCode": "MA" },
    { "name": "Mosaique FM", "countryCode": "TN" },
    { "name": "Shems FM", "countryCode": "TN" },
    { "name": "Chaîne 3", "countryCode": "DZ" },
    { "name": "Radio Algérie Internationale", "countryCode": "DZ" },
    { "name": "Radio Ajyal", "countryCode": "PS" },
    { "name": "Radio Raya", "countryCode": "PS" },
    { "name": "Al Rasheed FM", "countryCode": "IQ" },
    { "name": "Radio Dijla", "countryCode": "IQ" },
    { "name": "Yemen FM", "countryCode": "YE" },
    { "name": "Tripoli FM", "countryCode": "LY" },
    { "name": "Rotana Radio", "countryCode": "SA" },
    { "name": "NRJ Arab World", "countryCode": "AE" }
  ]
}
